//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaMonoBehaviourWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaMonoBehaviour), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetLuaObject", GetLuaObject);
		L.RegFunction("SetLuaObject", SetLuaObject);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLuaObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaMonoBehaviour obj = (LuaMonoBehaviour)ToLua.CheckObject(L, 1, typeof(LuaMonoBehaviour));
			LuaInterface.LuaTable o = obj.GetLuaObject();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLuaObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaMonoBehaviour obj = (LuaMonoBehaviour)ToLua.CheckObject(L, 1, typeof(LuaMonoBehaviour));
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.SetLuaObject(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

